anduril/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import home.site
import api.site
import groups.site


urlpatterns = [
    url(r"", include(home.site.urls, namespace="home")),
    url(r"^groups/", include(groups.site.urls, namespace="groups")),
    url(r"^api/", include(api.site.urls, namespace="api")),
    url(r"^admin/", admin.site.urls),
    url(r"^oauth/", include("oauth2_provider.urls", namespace="oauth2_provider")),
    url(r"^openid/", include("oidc_provider.urls", namespace="oidc_provider")),
]

core/models.py
"""Models shared by other Anduril applications.

This file primarily defines user and group profile objects, which vary,
via the polymorphic library, to serve as different types of each.
"""

from django.db import models
from polymorphic.models import PolymorphicModel
from django.contrib.auth import models as auth
from django.contrib.auth.signals import user_logged_in
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone

from lib.models import TimeTrackingModel


class UserManager(auth.UserManager):
    """User manager that modifies create for polymorphic profiles.
    
    A separate user manager is necessary to override User object
    create. Since we want to avoid any situations where a user
    object doesn't have a profile, we require it as a parameter.
    """

    def create_user(self, username, email=None, password=None, type: str=None, **extra_fields):
        """Create a user with an enumerated user profile type."""

        profile_fields = {}
        for field in tuple(extra_fields):
            if field.startswith("profile__"):
                profile_field = field[len("profile__"):]
                profile_fields[profile_field] = extra_fields.pop(field)

        user = User(username=username, **extra_fields)
        user.save()

        # Must be created here to use profile data
        profile = UserProfile.concrete[type](user=user, **profile_fields)
        profile.save()

        user.save()
        return user


class User(auth.User):
    """User proxy that overrides user create."""

    objects = UserManager()

    class Meta:
        proxy = True

    def __repr__(self):
        """Represent the user as a string."""

        try:
            return f"<{self.profile.type.capitalize()} {self.username}>"
        except AttributeError:
            return f"<User {self.username}>"

    __str__ = __repr__

    @property
    def slug(self):
        """Get the URL slug of the model."""

        return f"/users/{self.id}"


@receiver(post_save, sender=User)
def on_create_user(sender, instance, created, **kwargs):
    """Add members to the user when it is created."""

    if created:
        UserStatistics.objects.create(user=instance)
        return

    instance.profile.save()
    instance.statistics.save()


class UserProfile(PolymorphicModel, TimeTrackingModel):
    """Base user profile model."""

    # Enumerated profile types
    ABSTRACT = None
    STUDENT = "student"
    TEACHER = "teacher"
    COUNSELOR = "counselor"
    STAFF = "staff"
    ALUMNUS = "alumnus"

    TYPES = [STUDENT, TEACHER, COUNSELOR, STAFF, ALUMNUS]
    choices = map(lambda x: (x, x.capitalize()), TYPES)
    concrete = {}

    @staticmethod
    def register(type):
        """Register a profile class to a user enumeration."""

        def _register(cls):
            UserProfile.concrete[type] = cls
            cls.type = type
            return cls
        return _register

    def __init__(self, *args, **kwargs):
        """Initialize a user profile."""

        if "user" in kwargs:
            kwargs["user_id"] = kwargs["user"].id
        super().__init__(*args, **kwargs)

    # Actual profile fields
    user = models.OneToOneField(User, related_name="profile", on_delete=models.CASCADE)
    type = ABSTRACT

    middle_name = models.CharField(blank=True, null=True, max_length=60)
    display_first_name = models.CharField(blank=True, null=True, max_length=60)
    display_last_name = models.CharField(blank=True, null=True, max_length=60)

    @property
    def slug(self):
        """Get the URL slug of the model."""

        return self.user.slug

    @property
    def first_name(self):
        """Get the display first or first name of the user."""

        return self.display_first_name or self.user.first_name

    @property
    def last_name(self):
        """Get the display first or first name of the user."""

        return self.display_last_name or self.user.last_name

    @property
    def full_name(self):
        """Get the full name of the user."""

        return self.first_name + " " + self.last_name


class UserStatistics(models.Model):
    """User statistics object.
    
    This is here to collect arbitrary bits of data about site usage, 
    including login counts, first join date, etc.
    """

    user = models.OneToOneField(User, related_name="statistics", on_delete=models.CASCADE)
    first_login = models.DateTimeField(blank=True, null=True)
    login_count = models.IntegerField(default=0)

    def __repr__(self):
        """Represent the container as a string."""

        return f"<Statistics for {self.user.get_full_name()}>"


@receiver(user_logged_in)
def update_user_login_statistics(sender, user, request, **kwargs):
    """Called when a user logs into the system."""

    try:
        if user.statistics.login_count == 0:
            user.statistics.first_login = timezone.now()
        user.statistics.login_count += 1
        user.statistics.save()
    except UserStatistics.DoesNotExist:
        pass


@UserProfile.register(UserProfile.STUDENT)
class StudentUserProfile(UserProfile):
    """Student subclass of the user profile."""

    student_id = models.CharField(max_length=8, unique=True)
    graduation_year = models.IntegerField(blank=True, null=True)
    counselor = models.ForeignKey(User, blank=True, null=True)


@UserProfile.register(UserProfile.TEACHER)
class TeacherUserProfile(UserProfile):
    """Teacher subclass of the user profile."""


@UserProfile.register(UserProfile.COUNSELOR)
class CounselorUserProfile(UserProfile):
    """Counselor subclass of the user profile."""


@UserProfile.register(UserProfile.STAFF)
class StaffUserProfile(UserProfile):
    """Staff subclass of the user profile."""

    title = models.CharField(max_length=30)


@UserProfile.register(UserProfile.ALUMNUS)
class AlumnusUserProfile(UserProfile):
    """Staff subclass of the user profile."""

    graduation_year = models.IntegerField(blank=True, null=True)

home/models.py
from django.db import models
from django.contrib.auth.models import Permission, ContentType

from core.models import User
from groups.models import Group
from lib.models import TimeTrackingModel


class Friendship(TimeTrackingModel):
    """A friendship between two users."""

    a = models.ForeignKey(User, related_name="+")
    b = models.ForeignKey(User, related_name="+")
    confirmed = models.BooleanField(default=False)

    @staticmethod
    def between(a, b) -> bool:
        """Check if two users are friends."""

        return (Friendship.objects.filter(a=a, b=b, confirmed=True) |
                Friendship.objects.filter(a=b, b=a, confirmed=True)).first()

    @staticmethod
    def friends(user, confirmed=True) -> list:
        """Get all friends of a user."""

        ids = (set(Friendship.objects.filter(a=user, confirmed=confirmed).values_list("b", flat=True)) |
               set(Friendship.objects.filter(b=user, confirmed=confirmed).values_list("a", flat=True)))
        return User.objects.filter(pk__in=ids)


class Permissions(models.Model):
    """Permissions container not managed in the database."""

    class Meta:
        managed = False
        permissions = (
            ("can_login", "Can login to home"),)

groups/views/student.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, FormView

from groups import models


@login_required
def index(request):
    """View the index groups page."""

    return render(request, "groups/student/index.html", {"groups": request.user.groups.all()})


class List(ListView):
    """View the list of available groups."""

    model = models.Group
    template_name = "groups/list.html"
    context_object_name = "groups"
    paginate_by = 25

home/views/email.py
from django.contrib import auth
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, HttpResponse
from django.views.generic import View


class EmailView(LoginRequiredMixin, View):
    """Email submit and confirmation."""

    def get(self, request):
        """Get the email view."""

        return render(request, "home/email.html")

home/views/student.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib.auth.models import Permission

from core import models


def index(request, *args, **kwargs):
    """The index view for students."""

    return render(request, "home/student/index.html")


def profile(request, *args, **kwargs):
    """View the student profile."""

    return render(request, "home/student/profile.html")

home/templates/home/student/base.html
{% extends "home/base/base.html" %}
{% block sidebar %}
<div class="section">Dashboard</div>
<a class="item">News</a>
<a class="item">Courses</a>
<a class="item">Friends</a>
<div class="section">Groups</div>
<a class="item">Add groups...</a>
<div class="section">Counseling</div>
<a class="item">Meetings</a>
<div class="section">Account</div>
<a class="item">Profile</a>
<a class="item">Settings</a>
<a class="item" href="{% url "home:logout" %}">Logout</a>
{% endblock %}

home/templates/home/student/courses.html
{% extends "base/base.html" %}

{% block title %}Courses{% endblock %}

<h1>Sorry!</h1>
<p>
    Unfortunately, we're still waiting to discuss schedule access with the administration. It probably won't be back
any time soon, but we hope you stick with MBHS Home.
</p>

home/templates/home/student/index.html
{% extends "base/base.html" %}

{% block title %}Home{% endblock %}

{% block class %}home index{% endblock %}
{% block content %}
<h1>News</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In felis tellus, efficitur non rutrum quis, pretium sed odio. Fusce maximus augue in ligula mollis molestie. Aliquam quis massa suscipit, tristique nunc id, ultrices elit. Phasellus at tortor mollis, euismod enim et, hendrerit justo. Cras odio metus, aliquet in condimentum in, maximus eu orci. Praesent eleifend odio purus, eu elementum lorem faucibus non. Nam vel hendrerit lorem, ac imperdiet magna. Morbi aliquam vehicula sapien vel dictum. Nunc lobortis porttitor augue, malesuada posuere enim facilisis nec. In ac odio lectus. Nulla facilisis ex quis leo consequat cursus.</p>
<p>Donec ut consectetur lacus. Vestibulum molestie tempor nunc a tempus. Donec fermentum est eu neque volutpat lacinia. Pellentesque ultricies vel risus vitae hendrerit. Nulla auctor enim in tellus sodales venenatis. Donec tempor nulla vel ipsum fermentum sodales. Morbi sit amet eros libero.</p>
<p>Morbi at interdum mauris. Nunc venenatis semper metus, sit amet sodales metus euismod quis. Donec et commodo leo. Suspendisse egestas lacus at nulla semper, quis congue purus tincidunt. Sed tempus, leo rutrum porttitor pharetra, lectus orci consequat leo, quis consequat quam neque vitae nibh. Donec finibus lorem eu urna tristique sollicitudin. Fusce blandit ex lectus, eget scelerisque lorem gravida et. Duis quis efficitur urna. Vivamus eget dui ipsum. Integer vitae sem neque. Nulla in leo urna. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam volutpat condimentum porta. Proin ac odio laoreet ex eleifend pharetra.</p>
<p>Donec quis mollis risus. Nulla mattis commodo justo suscipit facilisis. Quisque suscipit consectetur tortor, sed convallis ligula sodales sed. Nunc ultricies pretium metus at malesuada. In orci enim, faucibus sit amet purus sed, maximus ornare nunc. Phasellus ullamcorper, odio facilisis bibendum vulputate, nulla leo placerat purus, sed gravida metus urna non magna. Cras molestie iaculis fringilla. Ut aliquet, lacus vitae imperdiet convallis, ex odio varius purus, ut convallis nulla massa a lacus. Maecenas est odio, maximus ac suscipit pharetra, efficitur in augue. Quisque ultrices id urna at ullamcorper. Sed dignissim felis et mattis pellentesque.</p>
<p>Donec ornare malesuada dolor, sit amet ultrices ante pharetra ac. Duis venenatis tincidunt magna, at egestas urna sodales eu. Etiam iaculis, justo sed pellentesque efficitur, ex dolor venenatis odio, ac rhoncus justo ex in sem. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam iaculis orci eget nulla imperdiet, ac facilisis mi euismod. Morbi suscipit vitae libero quis fermentum. Vestibulum non felis sed ligula pellentesque fringilla. Vivamus molestie odio nec facilisis imperdiet. Aliquam pulvinar ex dapibus leo tincidunt, nec egestas ex sodales. Phasellus ultrices tortor id tincidunt sodales. Nam volutpat est nec nisl fermentum, sit amet egestas eros interdum. Nullam in leo eget dolor ornare bibendum euismod id massa. Morbi luctus imperdiet lobortis. Morbi semper dolor quam, in ultricies lectus posuere ac. Nam scelerisque massa sit amet dui condimentum, eget auctor eros bibendum. Pellentesque condimentum sapien quis augue venenatis, non laoreet purus mollis.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In felis tellus, efficitur non rutrum quis, pretium sed odio. Fusce maximus augue in ligula mollis molestie. Aliquam quis massa suscipit, tristique nunc id, ultrices elit. Phasellus at tortor mollis, euismod enim et, hendrerit justo. Cras odio metus, aliquet in condimentum in, maximus eu orci. Praesent eleifend odio purus, eu elementum lorem faucibus non. Nam vel hendrerit lorem, ac imperdiet magna. Morbi aliquam vehicula sapien vel dictum. Nunc lobortis porttitor augue, malesuada posuere enim facilisis nec. In ac odio lectus. Nulla facilisis ex quis leo consequat cursus.</p>
<p>Donec ut consectetur lacus. Vestibulum molestie tempor nunc a tempus. Donec fermentum est eu neque volutpat lacinia. Pellentesque ultricies vel risus vitae hendrerit. Nulla auctor enim in tellus sodales venenatis. Donec tempor nulla vel ipsum fermentum sodales. Morbi sit amet eros libero.</p>
<p>Morbi at interdum mauris. Nunc venenatis semper metus, sit amet sodales metus euismod quis. Donec et commodo leo. Suspendisse egestas lacus at nulla semper, quis congue purus tincidunt. Sed tempus, leo rutrum porttitor pharetra, lectus orci consequat leo, quis consequat quam neque vitae nibh. Donec finibus lorem eu urna tristique sollicitudin. Fusce blandit ex lectus, eget scelerisque lorem gravida et. Duis quis efficitur urna. Vivamus eget dui ipsum. Integer vitae sem neque. Nulla in leo urna. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam volutpat condimentum porta. Proin ac odio laoreet ex eleifend pharetra.</p>
<p>Donec quis mollis risus. Nulla mattis commodo justo suscipit facilisis. Quisque suscipit consectetur tortor, sed convallis ligula sodales sed. Nunc ultricies pretium metus at malesuada. In orci enim, faucibus sit amet purus sed, maximus ornare nunc. Phasellus ullamcorper, odio facilisis bibendum vulputate, nulla leo placerat purus, sed gravida metus urna non magna. Cras molestie iaculis fringilla. Ut aliquet, lacus vitae imperdiet convallis, ex odio varius purus, ut convallis nulla massa a lacus. Maecenas est odio, maximus ac suscipit pharetra, efficitur in augue. Quisque ultrices id urna at ullamcorper. Sed dignissim felis et mattis pellentesque.</p>
<p>Donec ornare malesuada dolor, sit amet ultrices ante pharetra ac. Duis venenatis tincidunt magna, at egestas urna sodales eu. Etiam iaculis, justo sed pellentesque efficitur, ex dolor venenatis odio, ac rhoncus justo ex in sem. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam iaculis orci eget nulla imperdiet, ac facilisis mi euismod. Morbi suscipit vitae libero quis fermentum. Vestibulum non felis sed ligula pellentesque fringilla. Vivamus molestie odio nec facilisis imperdiet. Aliquam pulvinar ex dapibus leo tincidunt, nec egestas ex sodales. Phasellus ultrices tortor id tincidunt sodales. Nam volutpat est nec nisl fermentum, sit amet egestas eros interdum. Nullam in leo eget dolor ornare bibendum euismod id massa. Morbi luctus imperdiet lobortis. Morbi semper dolor quam, in ultricies lectus posuere ac. Nam scelerisque massa sit amet dui condimentum, eget auctor eros bibendum. Pellentesque condimentum sapien quis augue venenatis, non laoreet purus mollis.</p>
{% endblock %}

home/templates/home/student/profile.html
{% extends "base/base.html" %}

{% block content %}

{% endblock %}

home/templates/home/student/sidebar.html
<a class="item disabled">Dashboard</a>
<a class="item disabled">News</a>
<a class="item disabled">Courses</a>
<a class="item disabled">Friends</a>
<a class="item" href="{% url "groups:index" %}">Groups</a>
<div class="section">Groups</div>
{% if user.groups.length > 0 %}

{% else %}
    <a class="item" href="{% url "groups:list" %}">Add...</a>
{% endif %}
<div class="section">Account</div>
<a class="item" href="{% url "home:profile" %}">Profile</a>
<a class="item" href="{% url "oauth2_provider:list" %}">Applications</a>
<a class="item disabled">Settings</a>
<a class="item" href="{% url "home:logout" %}">Logout</a>